/**
 * ABOUTME: Evolution engine for ChoraForge.
 * Wraps the existing ExecutionEngine and ParallelExecutor with an outer
 * evolution loop that implements variant selection and blueprint-driven
 * gap analysis.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import type { Blueprint, BlueprintCriterion } from '../commands/blueprint.js';
import { loadBlueprint } from '../commands/blueprint.js';
import { UsageTracker, type UsageTrackerConfig } from './usage-tracker.js';
import { VariantScorer, type VariantDiff, type VariantScore, type VariantScorerConfig } from './variant-scorer.js';
import type { AgentPlugin } from '../plugins/agents/types.js';
import { VersionRegistry, captureScreenshot, type ScreenshotConfig } from './version-registry.js';

/**
 * Configuration for the evolution engine.
 */
export interface EvolutionConfig {
  /** Path to the blueprint file */
  blueprintPath: string;
  /** Maximum evolution versions to produce */
  maxVersions: number;
  /** Number of variants to spawn per task */
  variantsPerTask: number;
  /** Directory for evolution reports */
  reportsDir: string;
  /** Path to usage log */
  usageLogPath: string;
  /** Working directory */
  cwd: string;
  /** Model routing: task label → agent name */
  routing: Record<string, string>;
  /** Default agent name for unrouted tasks */
  defaultAgent: string;
  /** Agent instances by name */
  agents: Record<string, AgentPlugin>;
  /**
   * Usage tracking method override per agent name.
   * Defaults to 'rate-limit-detect' when not specified.
   * Use 'always-available' for high-quota providers (GLM, Kimi, local models)
   * that don't need back-off logic.
   */
  usageMethods?: Record<string, 'rate-limit-detect' | 'api-balance' | 'always-available'>;
  /** Agent to use for gap analysis and scoring (typically Opus) */
  architectAgent: AgentPlugin;
  /** Maximum workers for parallel execution */
  maxWorkers: number;
  /** Screenshot capture configuration (optional) */
  screenshot?: ScreenshotConfig;
  /** Display name for the app in the web UI */
  appName?: string;
}

/**
 * A task generated by gap analysis.
 */
export interface EvolutionTask {
  id: string;
  title: string;
  description: string;
  complexity: 'mechanical' | 'simple' | 'feature' | 'architecture' | 'review';
  criteriaIds: string[]; // Which AC-* items this task addresses
  priority: number;
}

/**
 * Report for a single evolution version.
 */
export interface EvolutionReport {
  version: number;
  timestamp: string;
  tasksGenerated: number;
  tasksCompleted: number;
  variantsSpawned: number;
  variantsSelected: number;
  criteriaMetBefore: string[];
  criteriaMetAfter: string[];
  criteriaDelta: string[];
  agentUsage: Record<string, number>;
  selectedVariants: VariantScore[];
  durationMs: number;
}

/**
 * Status of the evolution engine.
 */
export type EvolutionStatus = 'idle' | 'analyzing' | 'spawning' | 'scoring' | 'merging' | 'complete' | 'stopped';

/**
 * Event emitted by the evolution engine.
 */
export type EvolutionEvent =
  | { type: 'evolution:started'; maxVersions: number }
  | { type: 'evolution:version-started'; version: number }
  | { type: 'evolution:gap-analysis'; tasksGenerated: number }
  | { type: 'evolution:variants-spawned'; count: number }
  | { type: 'evolution:variant-scored'; score: VariantScore }
  | { type: 'evolution:variant-selected'; score: VariantScore }
  | { type: 'evolution:version-complete'; report: EvolutionReport }
  | { type: 'evolution:complete'; totalVersions: number }
  | { type: 'evolution:stopped'; reason: string }
  | { type: 'evolution:error'; error: string };

/**
 * The ChoraForge Evolution Engine.
 *
 * Outer loop:
 *   1. Gap analysis (Opus reads blueprint + codebase, generates tasks)
 *   2. Spawn variants (ParallelExecutor with N workers per task)
 *   3. Score variants (Opus reviews diffs against criteria)
 *   4. Merge best variant + tag version
 *   5. Check usage, repeat or stop
 */
export class EvolutionEngine {
  private config: EvolutionConfig;
  private blueprint: Blueprint | null = null;
  private usageTracker: UsageTracker;
  private variantScorer: VariantScorer;
  private versionRegistry: VersionRegistry;
  private status: EvolutionStatus = 'idle';
  private currentVersion = 0;
  private listeners: Array<(event: EvolutionEvent) => void> = [];

  /** Check if stopped (avoids TypeScript narrowing the status field in async loops). */
  private isStopped(): boolean {
    return this.status === 'stopped';
  }

  constructor(config: EvolutionConfig) {
    this.config = config;

    // Initialize usage tracker
    const usageConfig: UsageTrackerConfig = {
      logPath: config.usageLogPath,
      models: {},
    };
    for (const agentName of Object.keys(config.agents)) {
      const method = config.usageMethods?.[agentName] ?? 'rate-limit-detect';
      usageConfig.models[agentName] = {
        method,
        rateLimitCooldownMs: 60_000,
      };
    }
    this.usageTracker = new UsageTracker(usageConfig);

    // Initialize variant scorer
    const scorerConfig: VariantScorerConfig = {
      scoringAgent: config.architectAgent,
      cwd: config.cwd,
      timeout: 180_000, // 3 minutes for scoring
    };
    this.variantScorer = new VariantScorer(scorerConfig);

    // Initialize version registry
    this.versionRegistry = new VersionRegistry(config.cwd, config.appName);

    // Ensure directories exist
    if (!existsSync(config.reportsDir)) {
      mkdirSync(config.reportsDir, { recursive: true });
    }
  }

  /**
   * Subscribe to evolution events.
   */
  on(listener: (event: EvolutionEvent) => void): void {
    this.listeners.push(listener);
  }

  /**
   * Start the evolution loop.
   */
  async start(): Promise<void> {
    // Load blueprint
    this.blueprint = loadBlueprint(this.config.blueprintPath);
    if (!this.blueprint) {
      this.emit({ type: 'evolution:error', error: `Blueprint not found: ${this.config.blueprintPath}` });
      return;
    }

    this.status = 'idle';
    this.currentVersion = 0;
    this.emit({ type: 'evolution:started', maxVersions: this.config.maxVersions });

    // Main evolution loop
    while (this.currentVersion < this.config.maxVersions && !this.isStopped()) {
      this.currentVersion++;
      const startTime = Date.now();

      this.emit({ type: 'evolution:version-started', version: this.currentVersion });

      // Step 1: Gap Analysis
      this.status = 'analyzing';
      const tasks = await this.runGapAnalysis();

      if (tasks.length === 0) {
        this.emit({ type: 'evolution:complete', totalVersions: this.currentVersion - 1 });
        this.status = 'complete';
        return;
      }

      this.emit({ type: 'evolution:gap-analysis', tasksGenerated: tasks.length });

      // Step 2: Spawn Variants
      // In the full implementation, this would use ParallelExecutor.
      // For now, we generate the variant diff structure that the scorer expects.
      this.status = 'spawning';
      const variantDiffs = await this.spawnVariants(tasks);
      this.emit({ type: 'evolution:variants-spawned', count: variantDiffs.length });

      // Step 3: Score Variants
      this.status = 'scoring';
      const scores = await this.variantScorer.score(variantDiffs, this.blueprint);

      for (const score of scores) {
        this.emit({ type: 'evolution:variant-scored', score });
      }

      // Step 4: Select and Merge Best
      this.status = 'merging';
      const selected = this.variantScorer.selectBest(scores);
      const selectedVariants: VariantScore[] = [];

      if (selected) {
        this.emit({ type: 'evolution:variant-selected', score: selected });
        selectedVariants.push(selected);
        // In full implementation: git merge selected worktree branch
        // For now, the merge happens via ParallelExecutor's MergeEngine
      }

      // Step 5: Tag version
      this.tagVersion(this.currentVersion);

      // Step 6: Update criteria met status
      const criteriaMetBefore = this.blueprint.criteria
        .filter(c => c.met)
        .map(c => c.id);

      // Mark criteria as met based on selected variant
      if (selected) {
        for (const criterionId of selected.criteriaAddressed) {
          const criterion = this.blueprint.criteria.find(c => c.id === criterionId);
          if (criterion) criterion.met = true;
        }
      }

      const criteriaMetAfter = this.blueprint.criteria
        .filter(c => c.met)
        .map(c => c.id);

      // Step 7: Write evolution report
      const report: EvolutionReport = {
        version: this.currentVersion,
        timestamp: new Date().toISOString(),
        tasksGenerated: tasks.length,
        tasksCompleted: selectedVariants.length,
        variantsSpawned: variantDiffs.length,
        variantsSelected: selectedVariants.length,
        criteriaMetBefore,
        criteriaMetAfter,
        criteriaDelta: criteriaMetAfter.filter(c => !criteriaMetBefore.includes(c)),
        agentUsage: this.usageTracker.getSummary() as unknown as Record<string, number>,
        selectedVariants,
        durationMs: Date.now() - startTime,
      };

      this.writeReport(report);

      // Capture screenshot if configured
      let screenshotRelPath: string | null = null;
      if (this.config.screenshot?.enabled) {
        const screenshotFileName = `v0.${this.currentVersion}.png`;
        const screenshotAbsPath = join(this.versionRegistry.getScreenshotsDir(), screenshotFileName);
        const result = await captureScreenshot(this.config.screenshot, screenshotAbsPath);
        if (result) {
          screenshotRelPath = join('evolution', 'screenshots', screenshotFileName);
        }
      }

      // Record version in registry
      this.versionRegistry.recordVersion(report, screenshotRelPath);

      this.emit({ type: 'evolution:version-complete', report });

      // Step 8: Check if all criteria are met
      if (this.blueprint.criteria.every(c => c.met)) {
        this.emit({ type: 'evolution:complete', totalVersions: this.currentVersion });
        this.status = 'complete';
        return;
      }

      // Step 9: Check usage
      if (!this.usageTracker.anyAvailable()) {
        this.emit({ type: 'evolution:stopped', reason: 'All models exhausted' });
        this.status = 'stopped';
        return;
      }
    }

    this.emit({ type: 'evolution:complete', totalVersions: this.currentVersion });
    this.status = 'complete';
  }

  /**
   * Stop the evolution loop gracefully.
   */
  stop(): void {
    this.status = 'stopped';
    this.emit({ type: 'evolution:stopped', reason: 'User requested stop' });
  }

  /**
   * Get current evolution status.
   */
  getStatus(): { status: EvolutionStatus; version: number; blueprint: Blueprint | null } {
    return {
      status: this.status,
      version: this.currentVersion,
      blueprint: this.blueprint,
    };
  }

  /**
   * Get the version registry for accessing version history.
   */
  getVersionRegistry(): VersionRegistry {
    return this.versionRegistry;
  }

  /**
   * Run gap analysis: have the architect agent analyze the blueprint vs codebase
   * and generate tasks with complexity labels.
   *
   * In the full implementation, this executes the architect agent with a specialized
   * prompt. For now, this is a skeleton that returns tasks from the blueprint criteria.
   */
  private async runGapAnalysis(): Promise<EvolutionTask[]> {
    if (!this.blueprint) return [];

    // Find unmet criteria
    const unmetCriteria = this.blueprint.criteria.filter(c => !c.met);
    if (unmetCriteria.length === 0) return [];

    // Build gap analysis prompt
    const prompt = this.buildGapAnalysisPrompt(unmetCriteria);

    // Execute architect agent
    let output = '';
    const handle = this.config.architectAgent.execute(prompt, undefined, {
      cwd: this.config.cwd,
      timeout: 120_000,
      onStdout: (data: string) => { output += data; },
    });

    const result = await handle.promise;
    const fullOutput = output || result.stdout;

    // Parse tasks from output
    return this.parseGapAnalysisTasks(fullOutput, unmetCriteria);
  }

  /**
   * Build the gap analysis prompt for the architect agent.
   */
  private buildGapAnalysisPrompt(unmetCriteria: BlueprintCriterion[]): string {
    const criteriaList = unmetCriteria
      .map(c => `- ${c.id} [${c.priority}]: ${c.description}`)
      .join('\n');

    return `You are analyzing a codebase against a project blueprint to identify what work remains.

## Unmet Acceptance Criteria

${criteriaList}

## Instructions

1. Examine the codebase in the current working directory
2. For each unmet criterion, determine what specific implementation tasks are needed
3. Label each task with a complexity level:
   - \`mechanical\`: Type fixes, import corrections, lint fixes
   - \`simple\`: Small, focused changes (single file, clear scope)
   - \`feature\`: Multi-file feature implementation
   - \`architecture\`: Design decisions, schema changes, cross-cutting concerns
   - \`review\`: Code review, testing, validation

Output tasks as JSON array (no markdown fences):
[
  {
    "id": "T-1",
    "title": "Task title",
    "description": "What needs to be done",
    "complexity": "feature",
    "criteriaIds": ["AC-1"],
    "priority": 0
  }
]

After the JSON, say: <promise>COMPLETE</promise>`;
  }

  /**
   * Parse gap analysis output into EvolutionTask objects.
   */
  private parseGapAnalysisTasks(output: string, fallbackCriteria: BlueprintCriterion[]): EvolutionTask[] {
    const jsonMatch = output.match(/\[[\s\S]*?\]/);
    if (!jsonMatch) {
      // Fallback: create one task per unmet criterion
      return fallbackCriteria.map((c, i) => ({
        id: `T-${i + 1}`,
        title: `Implement ${c.id}: ${c.description.slice(0, 50)}`,
        description: c.description,
        complexity: 'feature' as const,
        criteriaIds: [c.id],
        priority: c.priority === 'P0' ? 0 : c.priority === 'P1' ? 1 : 2,
      }));
    }

    try {
      const parsed = JSON.parse(jsonMatch[0]) as EvolutionTask[];
      return parsed.map((task, i) => ({
        id: task.id || `T-${i + 1}`,
        title: task.title || `Task ${i + 1}`,
        description: task.description || '',
        complexity: task.complexity || 'feature',
        criteriaIds: task.criteriaIds || [],
        priority: typeof task.priority === 'number' ? task.priority : 1,
      }));
    } catch {
      return fallbackCriteria.map((c, i) => ({
        id: `T-${i + 1}`,
        title: `Implement ${c.id}: ${c.description.slice(0, 50)}`,
        description: c.description,
        complexity: 'feature' as const,
        criteriaIds: [c.id],
        priority: c.priority === 'P0' ? 0 : c.priority === 'P1' ? 1 : 2,
      }));
    }
  }

  /**
   * Spawn variants for each task using the configured agents.
   *
   * In the full implementation, this delegates to ParallelExecutor which
   * creates git worktrees and runs agents in parallel. For now, this
   * is a skeleton that creates the expected data structures.
   */
  private async spawnVariants(tasks: EvolutionTask[]): Promise<VariantDiff[]> {
    const variants: VariantDiff[] = [];

    for (const task of tasks) {
      // Route task to appropriate agent based on complexity label
      const routingKey = `complexity:${task.complexity}`;
      const agentName = this.config.routing[routingKey] ?? this.config.defaultAgent;

      // In full implementation: ParallelExecutor spawns N worktrees per task
      // with different agents, then we collect diffs
      for (let i = 0; i < this.config.variantsPerTask; i++) {
        // Record usage
        this.usageTracker.recordUsage({
          timestamp: new Date().toISOString(),
          agent: agentName,
          taskId: task.id,
          action: 'start',
        });

        variants.push({
          workerId: `worker-${variants.length}`,
          taskId: task.id,
          agentId: agentName,
          diff: '', // Will be populated by ParallelExecutor
          commitCount: 0,
        });
      }
    }

    return variants;
  }

  /**
   * Tag the current version in git.
   */
  private tagVersion(version: number): void {
    try {
      execSync(`git tag -a v0.${version} -m "Evolution version ${version}"`, {
        cwd: this.config.cwd,
        stdio: 'pipe',
      });
    } catch {
      // Tag might already exist or git might not be available
    }
  }

  /**
   * Write an evolution report to the reports directory.
   */
  private writeReport(report: EvolutionReport): void {
    const reportPath = join(
      this.config.reportsDir,
      `v0.${report.version - 1}-to-v0.${report.version}.md`
    );

    const content = [
      `# Evolution Report: v0.${report.version - 1} → v0.${report.version}`,
      '',
      `**Date**: ${report.timestamp}`,
      `**Duration**: ${(report.durationMs / 1000).toFixed(1)}s`,
      '',
      '## Tasks',
      `- Generated: ${report.tasksGenerated}`,
      `- Completed: ${report.tasksCompleted}`,
      '',
      '## Variants',
      `- Spawned: ${report.variantsSpawned}`,
      `- Selected: ${report.variantsSelected}`,
      '',
      '## Criteria Progress',
      `- Met before: ${report.criteriaMetBefore.join(', ') || 'none'}`,
      `- Met after: ${report.criteriaMetAfter.join(', ') || 'none'}`,
      `- New in this version: ${report.criteriaDelta.join(', ') || 'none'}`,
      '',
      '## Selected Variants',
      ...report.selectedVariants.map(v =>
        `- **${v.workerId}** (${v.agentId}): score ${v.qualityScore}, criteria: ${v.criteriaAddressed.join(', ')}\n  ${v.rationale}`
      ),
      '',
    ].join('\n');

    writeFileSync(reportPath, content);
  }

  /**
   * Emit an event to all listeners.
   */
  private emit(event: EvolutionEvent): void {
    for (const listener of this.listeners) {
      try {
        listener(event);
      } catch {
        // Don't let listener errors break the engine
      }
    }
  }
}

/**
 * Route a task to an agent name based on its complexity label and the routing config.
 */
export function routeTask(
  task: EvolutionTask,
  routing: Record<string, string>,
  defaultAgent: string
): string {
  const key = `complexity:${task.complexity}`;
  return routing[key] ?? defaultAgent;
}
